blueprint:
  name: Tasmota Detached Switch - Run actions on Switch1/Switch2 press (MQTT RESULT)
  description: >
    Run any Home Assistant actions (scripts, switches, lights, scenes, etc.) when a Tasmota device
    publishes Switch1/Switch2 events to its stat/<topic>/RESULT MQTT topic. Supports payloads:
    {"Switch1":"ON"}, {"Switch1":{"Action":"ON"}}, and TOGGLE variants.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT topic (RESULT)
      description: "Example: stat/shelly25/RESULT"
      selector:
        text:

    switch1_values:
      name: Switch1 trigger values
      description: Values that count as a "press" for Switch1
      default:
        - "ON"
        - "TOGGLE"
      selector:
        select:
          multiple: true
          options:
            - "ON"
            - "OFF"
            - "TOGGLE"
            - "HOLD"
            - "DOUBLE"
            - "SINGLE"
            - "1"
            - "0"

    switch2_values:
      name: Switch2 trigger values
      description: Values that count as a "press" for Switch2
      default:
        - "ON"
        - "TOGGLE"
      selector:
        select:
          multiple: true
          options:
            - "ON"
            - "OFF"
            - "TOGGLE"
            - "HOLD"
            - "DOUBLE"
            - "SINGLE"
            - "1"
            - "0"

    switch1_action:
      name: Action to run on Switch1 press
      selector:
        action: {}

    switch2_action:
      name: Action to run on Switch2 press
      selector:
        action: {}

mode: single

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

variables:
  s1_values: !input switch1_values
  s2_values: !input switch2_values

  # Extract Switch1 event value from either {"Switch1":"ON"} or {"Switch1":{"Action":"ON"}}
  s1: >-
    {% if trigger.payload_json is mapping %}
      {% set v = trigger.payload_json.get('Switch1') %}
      {% if v is mapping %}{{ v.get('Action') }}{% else %}{{ v }}{% endif %}
    {% else %}
      {{ none }}
    {% endif %}

  # Extract Switch2 event value
  s2: >-
    {% if trigger.payload_json is mapping %}
      {% set v = trigger.payload_json.get('Switch2') %}
      {% if v is mapping %}{{ v.get('Action') }}{% else %}{{ v }}{% endif %}
    {% else %}
      {{ none }}
    {% endif %}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ s1 is not none and (s1|string) in s1_values }}"
        sequence: !input switch1_action

      - conditions:
          - condition: template
            value_template: "{{ s2 is not none and (s2|string) in s2_values }}"
        sequence: !input switch2_action
